version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app/:/var/www/html/
  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: asuna
      MYSQL_USER: asuna
      MYSQL_PASSWORD: asuna
      MYSQL_ROOT_PASSWORD: asuna
    volumes:
      - ./docker/mariadb:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080